### Задача предсказания ССЗ (сердечно-сосудистых заболеваний)

https://mlbootcamp.ru/round/12/sandbox/

Целевая переменная - столбец cardio (есть в ssz_train и нет в ssz_test).

Формат ответа: 
"Загружаемое решение должно быть в формате csv, без заголовка. Поскольку мы оперируем лишь одним целевым признаком, фактически мы ожидаем от участников загрузку файла, где по порядку на каждой строке находится ***предсказание вероятности появления ССЗ для каждой из строк файла test.csv***".

Метрика: ***логарифмическая функция потерь (log-loss)***.

In [1]:
import pandas as pd

In [9]:
Train = pd.read_csv("ml5/ssz_train.csv", encoding='cp1252', delimiter=';')
Train.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,10.05.1950,2,168,62.0,110,80,1,1,0,0,1,0
1,1,19.05.1955,1,156,85.0,140,90,3,1,0,0,1,1
2,2,17.08.1951,1,165,64.0,130,70,3,1,0,0,0,1
3,3,31.03.1948,2,169,82.0,150,100,1,1,0,0,1,1
4,4,03.11.1947,1,156,56.0,100,60,1,1,0,0,0,0

In [10]:
Test = pd.read_csv("ml5/ssz_test.csv", encoding='cp1252', delimiter=';')
Test.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active
0,5,17.09.1951,1,154,85.0,130,80,1,1,0,0,1
1,6,18.02.1952,2,170,69.0,130,90,1,1,None,0,1
2,7,09.12.1955,1,160,70.0,120,75,1,1,0,0,0
3,10,23.08.1949,2,185,94.0,130,90,1,1,None,0,1
4,11,22.01.1944,2,170,76.0,120,80,1,1,0,0,1

### Шаг 1 (30 минут). 

Создайте простейшую модель, которая бы делала предсказания вероятностей для данной задачи.
Вычислите метрику качества вашей модели (log-loss) на кросс-валидации. Запомните значение метрики. Это будет ваше бейзлайновое решение.

In [ ]:
#your code here

### Шаг 2 (30 минут).

Обсудите с вашей группой возможные пути улучшения модели: 
    1) какую обработку данных можно сделать? 
    2) есть ли пропуски и чем их заполнить?
    3) какие новые числовые признаки можно извлечь из данных?
    
При необходимости в процессе обсуждения проводите исследование данных в python (стройте графики, считайте необходимые статистические характеристики и т.д.).

Все идеи по модели запишите в файл "Группа #" (где # - номер вашей группы): https://www.dropbox.com/sh/itdq86j72lltatr/AABlQRBwr0KC3i9vAQYfvX1ca?dl=0

In [ ]:
#your code here

### Шаг 3 (30 минут + Домашнее задание).

Послушайте советы других групп по решению данной задачи. Дома еще раз изучите все предложения, выберите для себя наиболее понравившиеся и на основе новых идей постройте модель.
Сделайте предсказание для тестовых данных (ssz_test.csv) и отправьте решение на лидерборд https://mlbootcamp.ru/round/12/sandbox/.
    Напишите в ноутбуке качество вашей модели, которое вы увидели на лидерборде.

In [ ]:
#your code here